name: Generate vim syntax ex
on:
  push:
    branches:
      - generator
  workflow_dispatch:
  schedule:
    - cron: '36 20 * * Sat'

# workflow_dispatch and schedule : work under master branch
# push - branches - generator    : work under generator branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Checkout generator
        uses: actions/checkout@v2
        with:
          ref: generator
          path: generator
          submodules: false
            # submodule need manual update: vim/vim is huge
      - name: Generate new syntax
        run: |
          cd generator
          git submodule update --init --recursive --recommend-shallow --depth 1
          make REVISION="$(date +%Y-%m-%dT%H:%M:%S%:z) $(git log -1 --format=%h)"
          make test
          cd ..
          cp -f generator/vim.vim syntax/vim.vim
          rm -rf generator
      - name: Commit updated master branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: |-
            Generated by GitHub workflow ${{ github.run_id }}

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          add: 'syntax/vim.vim'
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use below statement when check diff.
      #   if: steps.changes.outputs.count > 0
      # but always diff exists, because inserted time strings are different
      # - name: Check changes
      #   id: changes
      #   run: |
      #     echo "::set-output name=count::$(git diff --name-only | wc -l)"
